# Generated by Django 5.2 on 2025-05-22 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bloodbankbloods_bloodbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donated_date',
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
