[pytest]
DJANGO_SETTINGS_MODULE = RaktaPraptih.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --tb=short
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    database: marks tests that interact with the database