services:
  - type: web
    name: raktapraptih
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: RaktaPraptih.settings
      - key: DATABASE_URL
        value: ${DATABASE_URL}  # Set this to your Supabase PostgreSQL connection string
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOST
        value: raktapraptih.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false  # Set in Render dashboard
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false  # Set in Render dashboard
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false  # Set in Render dashboard