# Generated by Django 5.2 on 2025-05-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bloodbank_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankbloods',
            name='bloodbank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloodbankbloods', to='accounts.bloodbank'),
        ),
    ]
